name: build artifacts and push shit

on:
  push:
    branches:
      - main
jobs:
  generate_board_data:
    strategy:
      matrix:
        total: [20]
        shard:
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    timeout-minutes: 1440
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          mkdir home
      - name: build artifacts
        uses: addnab/docker-run-action@v3
        with:
          image: apertushq/eagle-docker:lngxymr611z4cqfyhy3r73ljl1chsgbf
          options: -v ${{ github.workspace }}:/src -e SHARD -e SHARD_TOTAL
          run: |
            echo $SHARD $SHARD_TOTAL
            mkdir /tmp
            cd /src
            python analyze.py
            python generate_info.py
            HOME=/src/home xvfb-run bash create_key_file.sh
            HOME=/src/home xvfb-run python gen.py $SHARD $SHARD_TOTAL
        env:
          SHARD: ${{ matrix.shard }}
          SHARD_TOTAL: ${{ matrix.total }}
      - name: convert to webp
        run: |
          sudo apt-get update -q && sudo apt-get install -y -q libwebp parallel
          cd boards
          find . -name *.png | parallel -j100% cwebp -lossless {} -o {.}.webp
      - uses: actions/upload-artifact@v2
        with:
          name: board_data-${{ matrix.shard }}
          path: |
            boards/*.zip
            boards/*.webp
            boards/*.pdf

  generate_webpage:
    needs: generate_board_data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: build webpage
        run: |
          sudo apt-get update -q && sudo apt-get install -y -q npm 
          mv board_data*/* boards
          cd web
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./web/dist
